// Country list with flag emoji for the region combobox.
window.COUNTRIES = [
  ["🇺🇸","United States"],["🇬🇧","United Kingdom"],["🇦🇺","Australia"],["🇨🇦","Canada"],["🇳🇿","New Zealand"],
  ["🇸🇬","Singapore"],["🇦🇪","United Arab Emirates"],["🇸🇦","Saudi Arabia"],["🇶🇦","Qatar"],["🇰🇼","Kuwait"],
  ["🇭🇰","Hong Kong SAR"],["🇯🇵","Japan"],["🇰🇷","South Korea"],["🇹🇼","Taiwan"],["🇨🇳","China"],
  ["🇮🇳","India"],["🇮🇩","Indonesia"],["🇲🇾","Malaysia"],["🇹🇭","Thailand"],["🇵🇭","Philippines"],
  ["🇻🇳","Vietnam"],["🇩🇪","Germany"],["🇫🇷","France"],["🇮🇹","Italy"],["🇪🇸","Spain"],
  ["🇵🇹","Portugal"],["🇳🇱","Netherlands"],["🇧🇪","Belgium"],["🇱🇺","Luxembourg"],["🇨🇭","Switzerland"],
  ["🇦🇹","Austria"],["🇮🇪","Ireland"],["🇸🇪","Sweden"],["🇳🇴","Norway"],["🇩🇰","Denmark"],
  ["🇫🇮","Finland"],["🇮🇸","Iceland"],["🇵🇱","Poland"],["🇨🇿","Czech Republic"],["🇸🇰","Slovakia"],
  ["🇭🇺","Hungary"],["🇷🇴","Romania"],["🇧🇬","Bulgaria"],["🇬🇷","Greece"],["🇹🇷","Turkey"],
  ["🇨🇾","Cyprus"],["🇲🇹","Malta"],["🇭🇷","Croatia"],["🇸🇮","Slovenia"],["🇷🇸","Serbia"],
  ["🇺🇦","Ukraine"],["🇱🇹","Lithuania"],["🇱🇻","Latvia"],["🇪🇪","Estonia"],["🇧🇷","Brazil"],
  ["🇦🇷","Argentina"],["🇨🇱","Chile"],["🇨🇴","Colombia"],["🇵🇪","Peru"],["🇺🇾","Uruguay"],
  ["🇲🇽","Mexico"],["🇵🇦","Panama"],["🇨🇷","Costa Rica"],["🇻🇪","Venezuela"],["🇪🇨","Ecuador"],
  ["🇵🇾","Paraguay"],["🇧🇴","Bolivia"],["🇩🇴","Dominican Republic"],["🇧🇸","Bahamas"],["🇧🇧","Barbados"],
  ["🇯🇲","Jamaica"],["🇹🇹","Trinidad & Tobago"],["🇰🇾","Cayman Islands"],["🇧🇲","Bermuda"],["🇻🇬","British Virgin Islands"],
  ["🇿🇦","South Africa"],["🇳🇬","Nigeria"],["🇰🇪","Kenya"],["🇪🇬","Egypt"],["🇲🇦","Morocco"],
  ["🇹🇳","Tunisia"],["🇬🇭","Ghana"],["🇪🇹","Ethiopia"],["🇺🇬","Uganda"],["🇹🇿","Tanzania"],
  ["🇷🇼","Rwanda"],["🇲🇺","Mauritius"],["🇸🇨","Seychelles"],["🇮🇱","Israel"],["🇯🇴","Jordan"],
  ["🇱🇧","Lebanon"],["🇴🇲","Oman"],["🇧🇭","Bahrain"],["🇵🇰","Pakistan"],["🇧🇩","Bangladesh"],
  ["🇱🇰","Sri Lanka"],["🇲🇻","Maldives"],["🇰🇭","Cambodia"],["🇱🇦","Laos"],["🇲🇲","Myanmar"],
  ["🇧🇳","Brunei"],["🇲🇳","Mongolia"],["🇰🇿","Kazakhstan"],["🇺🇿","Uzbekistan"],["🇦🇿","Azerbaijan"],
  ["🇬🇪","Georgia"],["🇦🇲","Armenia"],["🇰🇬","Kyrgyzstan"],["🇹🇯","Tajikistan"],["🇹🇲","Turkmenistan"],
  ["🇦🇱","Albania"],["🇧🇦","Bosnia & Herzegovina"],["🇲🇰","North Macedonia"],["🇲🇪","Montenegro"],["🇽🇰","Kosovo"],
  ["🇲🇩","Moldova"],["🇧🇾","Belarus"],["🇱🇮","Liechtenstein"],["🇲🇨","Monaco"],["🇦🇩","Andorra"],
  ["🇸🇲","San Marino"],["🇻🇦","Vatican City"],["🇬🇮","Gibraltar"],["🇬🇬","Guernsey"],["🇯🇪","Jersey"],
  ["🇮🇲","Isle of Man"],["🇫🇴","Faroe Islands"],["🇬🇱","Greenland"],["🇵🇫","French Polynesia"],["🇳🇨","New Caledonia"],
  ["🇫🇯","Fiji"],["🇵🇬","Papua New Guinea"],["🇼🇸","Samoa"],["🇹🇴","Tonga"],["🇻🇺","Vanuatu"],
  ["🇸🇧","Solomon Islands"],["🇲🇽","Mexico (Northern Region)"],["🌍","Other / Multiple"],
];
